# Generated by Django 5.2.8 on 2026-07-13 05:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAdMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='chat_ads/temp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'mov'])], verbose_name='Файл')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Изображение'), ('VIDEO', 'Видео')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_linked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ad_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Медиа рекламы',
                'verbose_name_plural': 'Медиа рекламы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAdOrder',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_name', models.CharField(max_length=255, verbose_name='Название заказа')),
                ('text', models.TextField(help_text='Основной текст рекламного сообщения', verbose_name='Текст рекламы')),
                ('link', models.CharField(help_text='URL для перехода по рекламе', verbose_name='Ссылка рекламы')),
                ('platform', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('NOVAGRAM', 'Novagram')], default='TELEGRAM', max_length=20, verbose_name='Платформа')),
                ('channels', models.TextField(help_text='Названия каналов через запятую (например: "channel1, channel2")', verbose_name='Каналы для показа')),
                ('spm', models.DecimalField(decimal_places=2, help_text='Стоимость за 1000 показов', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='SPM')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Бюджет')),
                ('total_views', models.PositiveIntegerField(default=0, help_text='Общее количество купленных показов', verbose_name='Всего показов')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Количество переходов по рекламе', verbose_name='Клики')),
                ('shown_views', models.PositiveIntegerField(default=0, help_text='Количество уже показанных просмотров', verbose_name='Показано просмотров')),
                ('remaining_views', models.PositiveIntegerField(default=0, help_text='Оставшееся количество показов', verbose_name='Оставшиеся показы')),
                ('max_views_per_user', models.IntegerField(default=-1, help_text='-1 означает без ограничений (показывать всегда)', verbose_name='Лимит показов на юзера')),
                ('completed', models.BooleanField(default=False, help_text='Реклама завершена (просмотры израсходованы)', verbose_name='Завершено')),
                ('cancelled', models.BooleanField(default=False, help_text='Реклама отменена пользователем', verbose_name='Отменено')),
                ('is_active', models.BooleanField(default=True, help_text='Реклама активна и показывается', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='chat_ads.chatadmedia', verbose_name='Медиа-вложение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реклама в чате',
                'verbose_name_plural': 'Реклама в чатах',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAdView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewer_id', models.CharField(db_index=True, help_text='ID пользователя, которому показывается реклама', max_length=255, verbose_name='ID пользователя')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Сколько раз пользователю показали эту рекламу', verbose_name='Количество просмотров')),
                ('clicked', models.BooleanField(default=False, help_text='Пользователь кликнул по рекламе', verbose_name='Кликнул')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, verbose_name='Последний просмотр')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Первый просмотр')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='chat_ads.chatadorder', verbose_name='Рекламный заказ')),
            ],
            options={
                'verbose_name': 'Показ рекламы в чате',
                'verbose_name_plural': 'Показы рекламы в чатах',
            },
        ),
        migrations.AddIndex(
            model_name='chatadorder',
            index=models.Index(fields=['is_active', 'completed'], name='chat_ads_ch_is_acti_eb2a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatadorder',
            index=models.Index(fields=['created_at'], name='chat_ads_ch_created_8f6839_idx'),
        ),
        migrations.AddIndex(
            model_name='chatadview',
            index=models.Index(fields=['viewer_id', 'order'], name='chat_ads_ch_viewer__5daba5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatadview',
            index=models.Index(fields=['last_viewed_at'], name='chat_ads_ch_last_vi_3067ae_idx'),
        ),
        migrations.AddIndex(
            model_name='chatadview',
            index=models.Index(fields=['first_viewed_at'], name='chat_ads_ch_first_v_aebd34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatadview',
            unique_together={('order', 'viewer_id')},
        ),
    ]
