# Generated by Django 5.2.8 on 2026-07-15 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def existing_orders_to_approved(apps, schema_editor):
    """
    Все заказы, созданные до появления модерации, считаем одобренными:
    работающие продолжают крутиться, а отменённые/завершённые и так
    защищены своими флагами cancelled/completed.
    """
    ChatAdOrder = apps.get_model('chat_ads', 'ChatAdOrder')
    ChatAdOrder.objects.all().update(status='APPROVED')


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatadorder',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда модерировали'),
        ),
        migrations.AddField(
            model_name='chatadorder',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто модерировал'),
        ),
        migrations.AddField(
            model_name='chatadorder',
            name='reject_reason',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Причина отклонения/блокировки'),
        ),
        migrations.AddField(
            model_name='chatadorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'На модерации'), ('APPROVED', 'Одобрен'), ('REJECTED', 'Отклонён'), ('BLOCKED', 'Заблокирован')], db_index=True, default='PENDING', max_length=10, verbose_name='Статус модерации'),
        ),
        migrations.AlterField(
            model_name='chatadorder',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Реклама активна и показывается. Включается только после одобрения модератором', verbose_name='Активно'),
        ),
        migrations.RunPython(existing_orders_to_approved, migrations.RunPython.noop),
    ]
