# Generated by Django 5.2.8 on 2026-07-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ads', '0003_alter_chatadorder_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatadorder',
            name='channels',
            field=models.TextField(blank=True, default='', help_text='Названия каналов через запятую (например: "channel1, channel2"). Пусто — показывать во всех каналах', verbose_name='Каналы для показа'),
        ),
    ]
