name: 'pro_messanger ads backend'

services:
  db:
    image: postgres:15-alpine
    container_name: channel_db_2
    environment:
      POSTGRES_DB: channel_db
      POSTGRES_USER: channel_user_2
      POSTGRES_PASSWORD: channel_pass123
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck: # Проверка готовности базы
      test: [ "CMD-SHELL", "pg_isready -U channel_user_2 -d channel_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: channel_redis
    restart: unless-stopped

  web:
    build: .
    container_name: channel_web_2
    command: >
      sh -c "
        echo 'Ждем базу данных...' &&
        sleep 5 &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn --bind 0.0.0.0:9000 --workers 3 core.wsgi:application
      "
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=True
#      - DEBUG=${DEBUG}
      - DATABASES_NAME=channel_db
      - DATABASES_USER=channel_user_2
      - DATABASES_PASSWORD=channel_pass123
      - DATABASES_HOST=db
      - DATABASES_PORT=5432
#      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - ALLOWED_HOSTS=localhost,127.0.0.1,185.203.241.191,nonmutational-hipolito-unravaged.ngrok-free.dev
      # Настройки для Celery внутри Docker (хост - имя сервиса 'redis')
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  celery_worker:
    build: .
    container_name: channel_worker
    command: celery -A core worker -l info
    volumes:
      - media_volume:/app/media # ОБЯЗАТЕЛЬНО: воркер должен видеть файлы, чтобы удалить их
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DATABASES_NAME=channel_db
      - DATABASES_USER=channel_user_2
      - DATABASES_PASSWORD=channel_pass123
      - DATABASES_HOST=db
      - DATABASES_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - web # Чтобы миграции точно прошли до запуска воркера
    restart: unless-stopped

  celery_beat:
    build: .
    container_name: channel_beat
    command: celery -A core beat -l info
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DATABASES_NAME=channel_db
      - DATABASES_USER=channel_user_2
      - DATABASES_PASSWORD=channel_pass123
      - DATABASES_HOST=db
      - DATABASES_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: channel_nginx_2
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
#      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume: