# Generated by Django 5.2.8 on 2025-12-16 06:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tag Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='order_name',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='spm',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='channel',
            name='tags',
        ),
        migrations.AlterField(
            model_name='channel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='User ID'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Balance Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, verbose_name='Channel Name')),
                ('order_name', models.CharField(max_length=255, verbose_name='Order Name')),
                ('spm', models.DecimalField(decimal_places=2, help_text='Spend per mille (стоимость за 1000 показов)', max_digits=10, verbose_name='SPM')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Budget')),
                ('total_views', models.PositiveIntegerField(default=0, help_text='Общее количество купленных показов', verbose_name='Total Views')),
                ('shown_views', models.PositiveIntegerField(default=0, help_text='Количество уже показанных просмотров', verbose_name='Shown Views')),
                ('remaining_views', models.PositiveIntegerField(default=0, help_text='Оставшееся количество показов', verbose_name='Remaining Views')),
                ('completed', models.BooleanField(default=False, help_text='True - реклама завершена (просмотры израсходованы)', verbose_name='Completed')),
                ('cancelled', models.BooleanField(default=False, help_text='True - реклама отменена пользователем', verbose_name='Cancelled')),
                ('is_active', models.BooleanField(default=True, help_text='True - реклама активна и показывается', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('tags', models.ManyToManyField(blank=True, related_name='orders', to='api.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='channels', to='api.tag'),
        ),
    ]
