# Generated by Django 5.2.8 on 2025-12-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_channel_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='max_views_per_user',
            field=models.PositiveIntegerField(default=1, help_text='Сколько раз можно показать эту рекламу одному пользователю', verbose_name='Максимальное количество показов одному пользователю'),
        ),
        migrations.CreateModel(
            name='AdView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_id', models.CharField(help_text='ID пользователя, которому показывается реклама', max_length=255, verbose_name='ID пользователя (зрителя)')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Сколько раз этому пользователю уже показали эту рекламу', verbose_name='Количество просмотров')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, verbose_name='Последний просмотр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_views', to='api.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Показ рекламы',
                'verbose_name_plural': 'Показы рекламы',
                'indexes': [models.Index(fields=['viewer_id', 'order'], name='api_adview_viewer__041470_idx'), models.Index(fields=['last_viewed_at'], name='api_adview_last_vi_ac18ce_idx')],
                'unique_together': {('order', 'viewer_id')},
            },
        ),
    ]
