# Generated by Django 5.2.8 on 2026-07-16 05:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('link', models.CharField(blank=True, default='', help_text='Куда ведёт тап по баннеру (https:// или tg://), можно пусто', max_length=500, verbose_name='Ссылка')),
                ('dismissible', models.BooleanField(default=True, help_text='False — баннер без крестика (важная информация)', verbose_name='Можно закрыть')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включен')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Показывать с')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Пусто — показывать, пока не выключат', null=True, verbose_name='Показывать до')),
                ('priority', models.IntegerField(default=0, help_text='Больше — выше в списке, клиент показывает первый', verbose_name='Приоритет')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Клики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_id', models.CharField(max_length=255, verbose_name='ID юзера в клиенте')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='announcements.announcement', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Закрытие баннера',
                'verbose_name_plural': 'Закрытия баннеров',
                'unique_together': {('announcement', 'viewer_id')},
            },
        ),
    ]
