# Generated by Django 5.2.8 on 2025-12-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag_alter_channel_options_remove_channel_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
