"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASES_NAME'),
        'USER': os.getenv('DATABASES_USER'),
        'PASSWORD': os.getenv('DATABASES_PASSWORD'),
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}
# Custom User Model
AUTH_USER_MODEL = 'api.CustomUser'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOW_ALL_ORIGINS = True
# Разрешаем куки (если нужна авторизация)
CORS_ALLOW_CREDENTIALS = True
# Разрешаем все заголовки (для разработки)
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
# Разрешаем все методы HTTP
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

# API Documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'Channel Management API',
    'DESCRIPTION': 'API for managing channels and orders',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # "SWAGGER_UI_SETTINGS": {
    #     "persistAuthorization": True,  # не сбрасывать авторизацию
    # },

    # # Автоматическое определение типов для SerializerMethodField
    # 'POSTPROCESSING_HOOKS': [
    #     'drf_spectacular.hooks.postprocess_schema_enums',
    #     'drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields',
    # ],
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2Njc0OTk0MiwiaWF0IjoxNzY2MTQ1MTQyLCJqdGkiOiI5OGYzMmNmNTBjNzk0N2MzYjQxZjExZjI0YWQ3MmRmMiIsInVzZXJfaWQiOiIzIn0.92zqRHyOMdyCKyc37H3A94_Epi35bV4q4WQGXn-qX4A",
  "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MjMxNTQyLCJpYXQiOjE3NjYxNDUxNDIsImp0aSI6IjhmNDE2ZTVmOTM2YTRmNzNiZjIwYzM3MWQyYjY0NjhhIiwidXNlcl9pZCI6IjMifQ.8e12YKKop62MvWDTs0_F6Sm_rGUIAKiZ7UgkWA8jO20",
  "user_id": "f67c58da-8112-41d7-b05c-0d25f6b2d70f",
  "username": "ulugbek",
  "is_admin": 'false'
}

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NjU3NDIwMCwiaWF0IjoxNzY1OTY5NDAwLCJqdGkiOiI2MTIyYzNlZDJiOTg0NTU3OWNkZWZjNDExNjYxNTI3MyIsInVzZXJfaWQiOiIxIn0.zKSEYd30EV6a6n-e_E60ud9jxEd17a_51JzvXt8EAZw",
  "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MDU1ODAwLCJpYXQiOjE3NjU5Njk0MDAsImp0aSI6ImVmM2RjMjFmMTBhZjQ0ZjRiZmZlMTJmOTRlMmVkOTYxIiwidXNlcl9pZCI6IjEifQ.kJ4Pobyey8hmpFr5LdhvPrUT8qLVm7DPE7klRSj6ptE",
  "user_id": "439e22b3-1a47-461f-a0fb-42ca9c0eaa55",
  "username": "admin",
  "is_admin": 'true'
}

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NjgxMDkyMywiaWF0IjoxNzY2MjA2MTIzLCJqdGkiOiIxMzFmZDA2NTFlZDY0NjNjODcxMzdiZmVmNmMzNmI0NCIsInVzZXJfaWQiOiI0In0.LoAkphYwGniQZXv-D6pZYO_ONxxfezDJ527q9EwWqKQ",
  "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MjkyNTIzLCJpYXQiOjE3NjYyMDYxMjMsImp0aSI6Ijg5NDQyMGRjMWNkMDQ5MWFhZWIzMmFjYmFmNzE3OGJhIiwidXNlcl9pZCI6IjQifQ.eVXiRMiHeOdybrpOhzgz_dcJ7_7p99Pq4xsjpkZe8Us",
  "user_id": "1133d289-42d9-4caf-8252-ba2d9657eb0e",
  "username": "harry",
  "is_admin": 'false'
}
