# Generated by Django 5.2.8 on 2026-07-13 05:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='ID канала (Telegram)')),
                ('channel_name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Имя канала (метка)')),
                ('claim_status', models.CharField(choices=[('UNCLAIMED', 'Не заявлен'), ('CONFIRMED', 'Подтверждён')], default='UNCLAIMED', max_length=10, verbose_name='Статус заявки')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждён')),
                ('available', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Доступно к выводу')),
                ('total_earned', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Заработано всего')),
                ('total_impressions', models.PositiveBigIntegerField(default=0, verbose_name='Показов оплачено')),
                ('share_rate', models.DecimalField(blank=True, decimal_places=3, help_text='Например 0.5 = 50%. Пусто — берётся значение по умолчанию.', max_digits=4, null=True, verbose_name='Доля площадки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_earnings', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Заработок канала',
                'verbose_name_plural': 'Заработок каналов',
                'ordering': ['-total_earned'],
            },
        ),
        migrations.CreateModel(
            name='EarningTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ACCRUAL', 'Начисление'), ('PAYOUT', 'Вывод')], max_length=10, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Сумма')),
                ('impressions', models.PositiveBigIntegerField(default=0, verbose_name='Показов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='partner.channelearning', verbose_name='Канал')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earning_transactions', to='chat_ads.chatadorder', verbose_name='Заказ-источник')),
            ],
            options={
                'verbose_name': 'Операция по заработку',
                'verbose_name_plural': 'Операции по заработку',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['channel', 'kind'], name='partner_ear_channel_d9c667_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel', 'order', 'kind'), name='uniq_accrual_per_channel_order')],
            },
        ),
    ]
