# Generated by Django 5.2.8 on 2026-07-15 11:32

from django.db import migrations, models


def is_admin_to_moderator(apps, schema_editor):
    """Бывшие is_admin=True становятся модераторами (пополнять балансы теперь может только суперадмин)"""
    CustomUser = apps.get_model('account', 'CustomUser')
    CustomUser.objects.filter(is_admin=True).update(role='MODERATOR')


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    # Порядок важен: сначала добавляем role, потом переносим данные из is_admin,
    # и только после этого удаляем старое поле
    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADVERTISER', 'Рекламодатель'), ('MODERATOR', 'Модератор')], default='ADVERTISER', help_text='Роль назначает суперадмин. Каждый новый пользователь — рекламодатель', max_length=20, verbose_name='Роль'),
        ),
        migrations.RunPython(is_admin_to_moderator, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
