# Generated by Django 5.2.8 on 2026-07-13 05:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Триграммный поиск тегов (TrigramSimilarity) требует расширения pg_trgm.
        # Создаём его здесь, чтобы на свежей БД поиск работал без ручного CREATE EXTENSION.
        TrigramExtension(),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя тега')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='channels', to='search_ads.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('channel_name', models.CharField(max_length=255, verbose_name='Channel Name')),
                ('order_name', models.CharField(max_length=255, verbose_name='Order Name')),
                ('platform', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('NOVAGRAM', 'Novagram')], default='TELEGRAM', max_length=20, verbose_name='Платформа')),
                ('spm', models.DecimalField(decimal_places=2, help_text='Spend per mille (стоимость за 1000 показов)', max_digits=10, verbose_name='SPM')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Budget')),
                ('total_views', models.PositiveIntegerField(default=0, help_text='Общее количество купленных показов', verbose_name='Total Views')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Количество переходов на канал по клику', verbose_name='Click channel')),
                ('shown_views', models.PositiveIntegerField(default=0, help_text='Количество уже показанных просмотров', verbose_name='Shown Views')),
                ('remaining_views', models.PositiveIntegerField(default=0, help_text='Оставшееся количество показов', verbose_name='Remaining Views')),
                ('max_views_per_user', models.PositiveIntegerField(default=1, help_text='Сколько раз можно показать эту рекламу одному пользователю', verbose_name='Максимальное количество показов одному пользователю')),
                ('completed', models.BooleanField(default=False, help_text='True - реклама завершена (просмотры израсходованы)', verbose_name='Completed')),
                ('cancelled', models.BooleanField(default=False, help_text='True - реклама отменена пользователем', verbose_name='Cancelled')),
                ('is_active', models.BooleanField(default=True, help_text='True - реклама активна и показывается', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='search_ads.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('tags', models.ManyToManyField(blank=True, related_name='orders', to='search_ads.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_id', models.CharField(help_text='ID пользователя, которому показывается реклама', max_length=255, verbose_name='ID пользователя (зрителя)')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Сколько раз этому пользователю уже показали эту рекламу', verbose_name='Количество просмотров')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, verbose_name='Последний просмотр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_views', to='search_ads.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Показ рекламы',
                'verbose_name_plural': 'Показы рекламы',
                'indexes': [models.Index(fields=['viewer_id', 'order'], name='search_ads__viewer__af1d01_idx'), models.Index(fields=['last_viewed_at'], name='search_ads__last_vi_aee022_idx')],
                'unique_together': {('order', 'viewer_id')},
            },
        ),
    ]
