# Generated by Django 5.2.8 on 2026-07-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_ads', '0002_order_moderated_at_order_moderated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='platform',
            field=models.CharField(choices=[('TELEGRAM', 'Telegram'), ('NOVAGRAM', 'Novagram')], default='NOVAGRAM', max_length=20, verbose_name='Платформа'),
        ),
    ]
