# Generated by Django 5.2.8 on 2026-07-17 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='FCM-токен')),
                ('platform', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=10, verbose_name='Платформа')),
                ('is_active', models.BooleanField(default=True, help_text='False — FCM сказал, что токен протух (приложение удалено)', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.CharField(max_length=1000, verbose_name='Текст')),
                ('type', models.CharField(choices=[('NEW_ORDER', 'Новый заказ на модерацию'), ('ORDER_APPROVED', 'Заказ одобрен'), ('ORDER_REJECTED', 'Заказ отклонён'), ('ORDER_BLOCKED', 'Заказ заблокирован')], max_length=20, verbose_name='Тип')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные для клиента')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
